apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bl45p
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: p45-beamline
  destination:
    name: argus
    namespace: p45-beamline
  source:
    path: apps
    repoURL: https://github.com/epics-containers/bl45p-apps.git
    targetRevision: switch-namespace
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
